import { StateGraph, START, END, MemorySaver } from '@langchain/langgraph';
import { HumanMessage, AIMessage, SystemMessage, ToolMessage, BaseMessage } from '@langchain/core/messages';
import { ChatOpenAI } from '@langchain/openai';
import { sql } from 'drizzle-orm';
import { db } from '../db';

// Define the shape of our conversational graph state
interface AgentState {
  messages: BaseMessage[];
  logs: Array<{ type: string; content: string }>;
  evaluationPasses: number;
  userId: string;
}

// Structured schema for our Senior DeepMind Critic evaluation output
interface EvaluationResult {
  is_accurate: boolean;
  critique: string;
  needs_more_data: boolean;
}

/**
 * Validates a SQL query for safety constraints and runs it directly on Vercel Postgres.
 * Forces read-only operations and appends defensive record limiters.
 * 
 * @param query Raw SQL query generated by the AI agent.
 * @param userId Scope database access strictly to this user's records.
 * @returns A string representation of the database rows or error details.
 */
async function queryDatabase(query: string, userId: string): Promise<string> {
  try {
    const uppercaseQuery = query.toUpperCase();
    const forbidden = ['DROP', 'DELETE', 'UPDATE', 'INSERT', 'ALTER', 'TRUNCATE', 'CREATE', 'RENAME'];
    
    if (forbidden.some((cmd) => uppercaseQuery.includes(cmd))) {
      return 'Error: Read-only access permitted.';
    }

    // Defense-in-depth: Ensure the query does not cross-contaminate user data
    if (!uppercaseQuery.includes(userId)) {
      return `Error: Query violates security sandbox. You MUST include \`user_id = '${userId}'\` in your WHERE filters.`;
    }

    let executableQuery = query;
    if (!uppercaseQuery.includes('LIMIT') && (uppercaseQuery.includes('SELECT *') || uppercaseQuery.includes('SELECT TEXT'))) {
      executableQuery += ' LIMIT 50';
    }

    // Execute raw SQL command via Drizzle ORM safely
    const result = await db.execute(sql.raw(executableQuery));
    const rows = result.rows;

    if (!rows || rows.length === 0) {
      return 'EMPTY_RESULT: The query returned no rows. The user likely has no data uploaded yet, or no records match the filter.';
    }

    return JSON.stringify(rows);
  } catch (error: any) {
    const msg: string = error.message || String(error);
    // Table doesn't exist — guide the user instead of showing a raw error
    if (msg.includes('relation') || msg.includes('does not exist') || msg.includes('42P01')) {
      return 'NO_TABLES: Database tables have not been created yet. The user needs to upload a dataset and process it first.';
    }
    return `SQL Error: ${msg}`;
  }
}

/**
 * Builds and initializes the LangGraph state machine.
 * Defines the execution flow: Generation ➔ Conditional Router ➔ Tool Execution / Critic Verification.
 * 
 * @param userId Scope db connection and query construction.
 * @returns Compiled executable state graph.
 */
function createAgentGraph(userId: string) {
  const groqKey = process.env.GROQ_API_KEY;
  const openRouterKey = process.env.OPENROUTER_API_KEY;
  const activeKey = groqKey || openRouterKey;

  if (!activeKey) {
    throw new Error('GROQ_API_KEY or OPENROUTER_API_KEY environment variable is required.');
  }

  const useGroq = !!groqKey;
  const modelName = useGroq ? 'llama-3.3-70b-versatile' : 'qwen/qwen3-235b-a22b:free';
  const configuration = useGroq ? {
    baseURL: 'https://api.groq.com/openai/v1',
  } : {
    baseURL: 'https://openrouter.ai/api/v1',
    defaultHeaders: {
      'HTTP-Referer': 'https://nexus-ai.local',
      'X-Title': 'Nexus AI',
    },
  };

  // Model setup
  const model = new ChatOpenAI({
    modelName,
    apiKey: activeKey,
    temperature: 0.1,
    configuration,
  });

  const evaluatorModel = new ChatOpenAI({
    modelName,
    apiKey: activeKey,
    temperature: 0.0,
    configuration,
  });

  // System instructions explaining roles and schema tables
  const dbSchemaInfo = `
  Table "datasets":
    - id (TEXT, Primary Key)
    - user_id (TEXT, Foreign Key)
    - filename (TEXT)
    - original_filename (TEXT)
    - row_count (INTEGER)
    - text_column (TEXT)
    - status (TEXT)
    - insights_json (TEXT)
    - created_at (TIMESTAMP)

  Table "records":
    - id (TEXT, Primary Key)
    - user_id (TEXT, Foreign Key)
    - dataset_id (TEXT, Foreign Key)
    - text (TEXT)
    - summary (TEXT)
    - sentiment (TEXT)
    - emotion (TEXT)
    - risk_level (TEXT)
    - confidence_score (REAL)
    - created_at (TIMESTAMP)
  `;

  const systemPrompt = `You are Nexus, an elite data analyst AI powering the Nexus AI platform. You provide C-Suite-level insights to executives and researchers.

You have access to a live SQL database. Use the \`query_database\` tool to run SELECT queries and get real data. Always query first, then answer.

DATABASE SCHEMA:
${dbSchemaInfo}

SECURITY: Every query MUST include \`user_id = '${userId}'\` in the WHERE clause. Never query other users' data.

RULES — follow these strictly:
1. ALWAYS call \`query_database\` to get real data before answering. Never fabricate or assume numbers.
2. Never show SQL queries, tool calls, or JSON in your response — only show the final analysis.
3. Never say "let's assume", "assuming the query returns", or invent hypothetical data.
4. If the tool returns EMPTY_RESULT, say: "No records found yet. Upload a CSV dataset and process it to see your data here."
5. If the tool returns NO_TABLES, say: "Your database isn't set up yet. Go to Upload Data, import a CSV, and run analysis first."
6. Write concise, natural prose. No unnecessary headers or lists unless the data warrants it.
7. Keep responses focused and conversational — avoid academic-style padding.
`;

  // Define graph channels
  const channels = {
    messages: {
      value: (x: BaseMessage[], y: BaseMessage[]) => x.concat(y),
      default: () => [],
    },
    logs: {
      value: (x: any[], y: any[]) => x.concat(y),
      default: () => [],
    },
    evaluationPasses: {
      value: (x: number, y: number) => y,
      default: () => 0,
    },
    userId: {
      value: (x: string, y: string) => y,
      default: () => userId,
    }
  };

  // Node 1: AI response generator
  const generateNode = async (state: AgentState) => {
    const activeMessages = [new SystemMessage(systemPrompt), ...state.messages];
    const response = await model.invoke(activeMessages);
    
    const newLogs: Array<{ type: string; content: string }> = [];
    if (response.additional_kwargs?.tool_calls) {
      const calls = response.additional_kwargs.tool_calls as any[];
      calls.forEach((t) => {
        try {
          const args = typeof t.function.arguments === 'string' ? JSON.parse(t.function.arguments) : t.function.arguments;
          newLogs.push({ type: 'thought', content: `Querying DB: ${args.query || JSON.stringify(args)}` });
        } catch {
          newLogs.push({ type: 'thought', content: 'Formulating SQL database query...' });
        }
      });
    } else {
      newLogs.push({ type: 'thought', content: 'Analyzing findings for final response.' });
    }

    return {
      messages: [response],
      logs: newLogs,
    };
  };

  // Node 2: Database tool call executor
  const executeToolsNode = async (state: AgentState) => {
    const lastMsg = state.messages[state.messages.length - 1] as AIMessage;
    const toolCalls = lastMsg.additional_kwargs?.tool_calls as any[] || [];
    const toolMessages: BaseMessage[] = [];
    const newLogs: Array<{ type: string; content: string }> = [];

    for (const call of toolCalls) {
      const name = call.function.name;
      if (name === 'query_database') {
        const args = typeof call.function.arguments === 'string' ? JSON.parse(call.function.arguments) : call.function.arguments;
        const query = args.query;
        
        const result = await queryDatabase(query, userId);
        
        toolMessages.push(new ToolMessage({
          content: result,
          tool_call_id: call.id,
          name: 'query_database',
        }));

        newLogs.push({
          type: 'tool_result',
          content: `SQL Result: ${result.slice(0, 200)}...`,
        });
      }
    }

    return {
      messages: toolMessages,
      logs: newLogs,
    };
  };

  // Node 3: Senior DeepMind Critic for hallucination checking and quality validation
  const criticNode = async (state: AgentState) => {
    const messages = state.messages;
    const lastMsg = messages[messages.length - 1];

    // If the last step contains tool executions, skip the evaluation pass
    if (lastMsg.additional_kwargs?.tool_calls) {
      return {};
    }

    const userQuestion = [...messages]
      .reverse()
      .find((m) => m instanceof HumanMessage)?.content || 'Analyze datasets';

    const criticPrompt = `You are a Senior DeepMind Critic. Evaluate if the assistant's response is factually grounded in the provided SQL data. 
If the AI didn't use the database but should have to answer the question, mark it as inaccurate.
Return a JSON object:
{
  "is_accurate": true | false,
  "critique": "Detailed factual and semantic grounding explanation",
  "needs_more_data": true | false
}

User Question: ${userQuestion}
AI Response: ${lastMsg.content}

Return ONLY raw JSON, no markdown code fences, no leading comments.`;

    const newLogs: Array<{ type: string; content: string }> = [];
    let isAcc = true;
    let critique = 'Grounding check passed.';

    try {
      const evalRes = await evaluatorModel.invoke([
        new SystemMessage('You are a factual verification evaluator. You output ONLY raw JSON.'),
        new HumanMessage(criticPrompt),
      ]);

      const parsed = JSON.parse(evalRes.content as string) as EvaluationResult;
      isAcc = parsed.is_accurate;
      critique = parsed.critique;
    } catch (e: any) {
      console.error('Critic node encountered an evaluation parsing error:', e);
      isAcc = true; // Fallback to avoid deadlocks on transient schema deviations
    }

    newLogs.push({
      type: 'critique',
      content: `${isAcc ? 'PASS' : 'FAIL'}: ${critique}`,
    });

    // If verification fails, append critique instruction to self-correct
    if (!isAcc && state.evaluationPasses < 1) {
      const feedbackMsg = new HumanMessage(
        `[INTERNAL SELF-CRITIQUE]: Your answer has database grounding issues: ${critique}. Please revise, call standard database tools to pull accurate stats, and rewrite.`
      );
      return {
        messages: [feedbackMsg],
        logs: newLogs,
        evaluationPasses: state.evaluationPasses + 1,
      };
    }

    return {
      logs: newLogs,
      evaluationPasses: state.evaluationPasses + 1,
    };
  };

  // State Transition Routing Logic
  const generateRouter = (state: AgentState): 'tools' | 'critic' => {
    const lastMsg = state.messages[state.messages.length - 1];
    if (lastMsg.additional_kwargs?.tool_calls && lastMsg.additional_kwargs.tool_calls.length > 0) {
      return 'tools';
    }
    return 'critic';
  };

  const criticRouter = (state: AgentState): 'generate' | typeof END => {
    const lastMsg = state.messages[state.messages.length - 1];
    if (lastMsg instanceof HumanMessage && lastMsg.content.toString().includes('[INTERNAL SELF-CRITIQUE]')) {
      return 'generate';
    }
    return END;
  };

  // Compile State Graph
  const builder = new StateGraph<AgentState>({ channels })
    .addNode('generate', generateNode)
    .addNode('tools', executeToolsNode)
    .addNode('critic', criticNode)
    .addEdge(START, 'generate')
    .addConditionalEdges('generate', generateRouter)
    .addEdge('tools', 'generate')
    .addConditionalEdges('critic', criticRouter);

  return builder.compile({ checkpointer: new MemorySaver() });
}

/**
 * Runs a multi-turn chat interaction with the SQL Agent using thread persistence.
 * 
 * @param messagesList Array of plain messages from client.
 * @param userId Scope analysis to target user database.
 * @param threadId Optional thread identifier for multi-turn persistence.
 * @returns An array holding the assistant response string and the execution logs list.
 */
export async function runChat(
  messagesList: Array<{ role: 'user' | 'assistant' | 'system'; content: string }>,
  userId: string,
  threadId: string = 'default'
): Promise<[string, Array<{ type: string; content: string }>]> {
  const agent = createAgentGraph(userId);
  const config = { configurable: { thread_id: threadId } };

  // Translate roles into proper LangChain Message instances
  const parsedMessages: BaseMessage[] = [];
  
  // If starting a fresh thread, seed with the system prompt
  if (messagesList.length <= 1) {
    parsedMessages.push(new SystemMessage('System prompt seed'));
  }

  messagesList.forEach((m) => {
    if (m.role === 'user') {
      parsedMessages.push(new HumanMessage(m.content));
    } else if (m.role === 'assistant') {
      parsedMessages.push(new AIMessage(m.content));
    }
  });

  const latestUserMessage = messagesList
    .slice()
    .reverse()
    .find((m) => m.role === 'user')?.content || '';

  const inputState = {
    messages: [new HumanMessage(latestUserMessage)],
    logs: [],
    evaluationPasses: 0,
    userId,
  };

  const finalState = (await agent.invoke(inputState, config)) as unknown as AgentState;

  // Walk back to find the last AIMessage with actual prose content, skipping tool-call stubs.
  let finalMessage = 'Analysis complete. Please ask a specific question about your data.';
  const allMsgs = finalState.messages;
  for (let i = allMsgs.length - 1; i >= 0; i--) {
    const msg = allMsgs[i];
    if (!(msg instanceof AIMessage)) continue;
    const hasText = typeof msg.content === 'string' && msg.content.trim().length > 0;
    const isToolCall = !!(msg.additional_kwargs?.tool_calls?.length);
    if (hasText && !isToolCall) {
      finalMessage = msg.content as string;
      break;
    }
  }

  // Strip any leaked tool-call JSON blocks or "SQL Query" sections the model wrote as text
  finalMessage = finalMessage
    // Remove fenced code blocks containing tool call JSON
    .replace(/```[\w]*\s*\{[\s\S]*?"name"\s*:\s*"query_database"[\s\S]*?\}\s*```/gi, '')
    // Remove bare JSON objects that look like tool calls
    .replace(/\{[\s\S]*?"name"\s*:\s*"query_database"[\s\S]*?\}/g, '')
    // Remove "SQL Query" header sections that precede a code block
    .replace(/#{1,4}\s*SQL\s*Query[\s\S]*?(?=\n#{1,4}|\n\n[A-Z]|$)/gi, '')
    // Remove "let's assume" hallucination preambles
    .replace(/let['']s assume[\s\S]*?(?=\n#{1,4}|\n\nBased on|$)/gi, '')
    .trim();

  const logs = finalState.logs || [];

  return [finalMessage, logs];
}
